Django-Project/project_02/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.movie_list, name = 'movie_list'),
    path('<int:movie_id>/', views.movie_detail, name= 'movie_detail'),
    path('<int:movie_id>/delete/', views.delete_movie, name= 'delete_movie'),
    path('<int:movie_id>/scores/new', views.create_score, name='create_score'),
    path('<int:movie_id>/scores/<int:score_id>/delete', views.delete_score, name='delete_score'),
    path('new/',views.new, name='new'),
    path('<int:movie_id>/edit/', views.edit_movie, name='edit_movie'),
]

Django-Project/project_02/project_02/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
]

Django-Project/project_02/movies/models.py
from django.db import models

# Create your models here.
class Genre(models.Model) :
    name = models.TextField(default='')

class Movie(models.Model) :
    title = models.TextField(default="")
    audience = models.IntegerField()
    poster_url = models.TextField(default = '')
    description =models.TextField(default='')
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

class Score(models.Model) :
    content = models.TextField(default='')
    score = models.IntegerField()
    movie = models.ForeignKey(Movie,on_delete=models.CASCADE)

Django-Project/project_02/movies/forms.py
from django import forms
from .models import Movie

class MovieModelForm(forms.ModelForm) :
    class Meta :
        model = Movie
        fields = ['title', 'audience','poster_url','description','genre']
        # TODO : 장르, 포스터 수정
        widgets = {
            'title' : forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': '제목을 입력해주세요.'
                }),
            'audience': forms.NumberInput(
                attrs={
                    'class': 'form-control'
                }),
            'poster_url': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }),
            'genre': forms.TextInput(
                attrs={
                    'class': 'form-control'
                })
        }

Django-Project/project_02/movies/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Movie, Genre, Score
from .forms import MovieModelForm
from django.contrib import messages

# Create your views here.
def movie_list(request):
    movies = Movie.objects.all()
    return render(request, 'movies/list.html',{
        'movies': movies
    })

def movie_detail(request, movie_id) :
    movie = get_object_or_404(Movie, id=movie_id)
    scores = movie.score_set.all()
    return render(request, 'movies/detail.html',{
        'movie' : movie,
        'scores' : scores
    })

def delete_movie(request, movie_id) :
    if request.method == 'POST' :
        movie = get_object_or_404(Movie, id=movie_id)
        movie.delete()
    return redirect('movies:movie_list')

def create_score(request, movie_id) :
    movie = get_object_or_404(Movie, id=movie_id)
    if request.method == 'POST':
        score = Score()
        score.score = request.POST.get('score')
        score.content = request.POST.get('content')
        score.movie_id = movie.id
        score.save()
    return redirect('movies:movie_detail',movie.id)


def delete_score(request, movie_id, score_id) :
    if request.method == 'POST' :
        score = get_object_or_404(Score, id=score_id)
        score.delete()

    return redirect('movies:movie_detail', movie_id)

def new(request) :
    if request.method == "POST" :
        form = MovieModelForm(request.POST)
        if form.is_valid() :
            form.save()
            return redirect('movies:movie_detail', form.instance.id)
    else :
        # form을 보여준다.
        form = MovieModelForm()
    return render(request, 'movies/form.html', {'form':form})

def edit_movie(request, movie_id) :
    movie = Movie.objects.get(pk=movie_id)
    if request.method == 'POST' :
        # 저장
        form = MovieModelForm(request.POST, instance=movie)
        if form.is_valid() :
            form.save()
            return redirect('movies:movie_detail', form.instance.id)
        messages.success(request, '유효하지 않은 데이터입니다.')
    else :
        # 수정페이지
        form = MovieModelForm(instance=movie)
    return render(request, 'movies/form.html', {'form':form})

Django-Project/project_02/movies/templates/movies/_score.html
<div class="score mt-3">
<p>평점 및 댓글 등록</p>
    <div class="score-form">
        <form action="{% url 'movies:create_score' movie.id %}" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-2">
                    <label for="inputCity" class="sr-only">score</label>
                    <input type="number" name="score" class="form-control"
                           id="score">
                </div>
                <div class="form-group col-7">
                    <label for="content" class="sr-only">content</label>
                    <input type="text" name="content" class="form-control" id="content">
                </div>
                <div class="form-group col-3">
                    <button type="submit" class="btn btn-primary">댓글 등록</button>
                </div>
            </div>
        </form>
    </div>
    {% if scores %}
        <div class="score-list">
            {% for score in scores %}
                <div class="row text-right">
                    <p class="col-2">{{ score.score }} 점</p>
                    <p class="col-7">{{ score.content }}</p>
                    <form action="{% url 'movies:delete_score' movie.id score.id %}" method="POST">
                        {% csrf_token %}
                        <button class="btn btn-outline-secondary btn-sm">삭제</button>
                    </form>
                </div>
            {% endfor %}
        </div>
    {% endif %}
</div>

Django-Project/project_02/movies/templates/movies/base.html
<!doctype html>
<html lang="KO">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <title>{% block title %}
                                
    {% endblock %}</title>
</head>
<body>
<!-- nav bar -->
<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
      <a class="nav-link {% block is_list %}{% endblock %}" href="{% url 'movies:movie_list' %}" >영화목록</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {% block is_detail %}{% endblock %}" href="" >상세보기</a>
  </li>
</ul>
{% if messages %}
    <!-- 메시지를 보여준다 -->
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      {% for message in messages %}
        {{ message }}
      {% endfor %}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %}
{% block body %}
{% endblock %}

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

Django-Project/project_02/movies/templates/movies/detail.html
{% extends 'movies/base.html' %}
{% block is_detail %}
active
{% endblock %}
{% block title %}
    영화 상세 정보
{% endblock %}
{% block body %}
    {% if movie %}
        <div class="container">
            <div class="row align-item-center mt-5">
                <div class="col-md-4 mb-2">
                    <img src="{{ movie.poster_url }}" class="card-img-top" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="movie-desc">
                        <h5 class="card-title">{{ movie.title }}</h5>
                        <p>
                            장르: {{ movie.genre.name }}
                            <br/>
                            누적관객수: {{ movie.audience }}
                        </p>
                        <p class="card-text">{{ movie.description }}</p>
                    </div>
                    <div class="movie-btn text-right mt-5">
                        <!-- 영화 수정 버튼 -->
                        <a href="{% url 'movies:edit_movie' movie.id %}">
                            <button type="submit" class="btn btn-primary">수정</button>
                        </a>
                        <!-- 영화 삭제 버튼 -->
                        <form action="{% url 'movies:delete_movie' movie.id %}" method="POST">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">삭제</button>
                        </form>
                    </div>
                    <hr/>
                    <!-- score block -->
                    {% include 'movies/_score.html' %}
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

Django-Project/project_02/movies/templates/movies/form.html
{% extends 'movies/base.html' %}

{% block body %}
    <div class="col-md-6 offset-md-3">
        <form method="POST">
            {%  csrf_token %}
            {{ form.as_p }}
            <input type="submit" />
        </form>
    </div>
{% endblock %}

Django-Project/project_02/movies/templates/movies/list.html
{% extends 'movies/base.html' %}
{% block is_list %}
active
{% endblock %}
{% block title %}
    영화목록
{% endblock %}
{% block body %}
    <div class="container">
        <a href="{% url 'movies:new' %}"><button class="btn btn-primary">영화 생성</button></a>
        <section class="card-columns mt-5">
                {% if movies %}
                    {% for movie in movies %}
                        <article class="card" style="width: 18rem;">
                            <img src="{{ movie.poster_url }}" class="card-img-top" alt="...">
                            <div class="card-body">
                                <a href="{% url 'movies:movie_detail' movie.id %}">
                                    <h5 class="card-title">{{ movie.title }}</h5>
                                </a>
                                <p class="card-text">{{ movie.genre.name }}</p>
                                <p class="card-text">{{ movie.description }}</p>
                            </div>
                        </article>
                    {% endfor %}
                {% endif %}
        </section>
    </div>
{% endblock %}