Django-Project/project_01/board/urls.py
from django.urls import path
from . import views

app_name = "board"

urlpatterns = [
    path('',views.article_list,name='article_list'),
    path('<int:article_id>/', views.article_detail, name='article_detail'),
    # path('new/',views.new_article, name = 'new_article'),
    path('create/',views.create_article,name='create_article'),
    path('<int:article_id>/update/',views.update_article, name= 'update_article'),
    path('<int:article_id>/delete/',views.delete_article, name='delete_article'),
    # board/1/comment/create
    path('<int:article_id>/comments/create',views.create_comment,name='create_comment'),
    # board/1/comment/1/delete
    path('<int:article_id>/comments/<int:comment_id>/delete',views.delete_comment,name='delete_comment'),
]

Django-Project/project_01/project_01/urls.py
from django.contrib import admin
from django.urls import path, include

# 파일업로드
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('sns/',include('sns.urls')),
]

# dev에서는 꼭 써야 함. (DEBUG='TRUE')
# 배포(DEBUG='False')상태에서는 빈 배열이 들어오는데 += 연산이므로 영향이 없다.
# 꼭 써주는 것이 좋다.
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django-Project/project_01/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    path('',views.posting_list,name='posting_list'),
    path('<int:posting_id>/',views.posting_detail, name='posting_detail'),
    path('create/',views.create_posting, name='create_posting'),
    path('<int:posting_id>/comment/create/',views.create_comment, name= 'create_comment'),
]

Django-Project/project_01/board/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=200, default='')
    content = models.TextField(default='')
    like = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.id} {self.title[:22]}'

class Comment(models.Model) :
    article = models.ForeignKey(Article,on_delete=models.CASCADE)
    content = models.CharField(max_length=100, default="")

    def __str__(self):
        return f'{self.article_id.title}: {self.content[:20]}'

Django-Project/project_01/sns/models.py
from django.db import models

#imagekit
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import ResizeToFit

# Create your models here.
class Posting(models.Model) :
    content = models.TextField(default='')
    icon = models.CharField(max_length=20, default='')

    # save as origin
    # image = models.ImageField(blank=True, upload_to='postings/%y/%m/%d')
    image = ProcessedImageField(
        blank=True,
        upload_to='postings/resize/%y/%m/%d',
        processors=[ResizeToFit(width=960,upscale=False)],
        format='JPEG'
    )

    # 썸네일 이미지
    # 사용자로부터 이미지를 받아오는 것이 아니므로 upload_to옵션을 사용하지 않음
    # source의 값에는 이미지를 가지고 있는 칼럼이름!
    image_thumbnail =ImageSpecField(
        source='image',
        processors=[ResizeToFit(width=320,upscale=False)],
        format='JPEG',
        options={'quality':60}
    )
    # auto_now_add : 생성되고 나서 한번만 기록, 
    # auto_now : 생성 이후로도 수정될때도 기록
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.id}:{self.content[:20]}'

    # DB 저장시, 로그찍기
    def save(self, *args, **kwargs):
        # 일단 원래하던 save() 수행
        super().save(*args,**kwargs)
        # 로그 찍기
        print()
        print(f'=== Saved Posting with id: {self.id} ===')
        print(f'    content: {self.content}')
        if self.image :
            print(f'    image: {self.image.width}.px * {self.image.height}.px : {self.image.size/1024} kb')
        print(f'=================================')


class Comment(models.Model) :
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE)
    content = models.CharField(max_length=100, default="")
    create_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.posting.content[:20]}:{self.content[:20]}'

Django-Project/project_01/board/views.py
from django.shortcuts import render, get_object_or_404, redirect
from board.models import Article, Comment
from IPython import embed

# Create your views here.
def article_list(request):
    articles = Article.objects.all().order_by('-id')
    return render(request,'board/list.html',{
        "articles" : articles
    })

def article_detail(request, article_id):

    article = get_object_or_404(Article,id=article_id)
    comments = article.comment_set.all()
    return render(request,'board/detail.html',{
        'article':article,
        'comments':comments
    })

def create_article(request) :
    if request.method == 'GET' :
        return render(request, 'board/new.html')
    elif request.method == 'POST' :
        article = Article()
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('board:article_detail', article.id)

def delete_article(request, article_id) :
    # 해당 값이 존재하는지 먼저 확인
    if request.method == "POST" :
        article = get_object_or_404(Article, id= article_id)
        article.delete()
        return redirect('board:article_list')
    elif request.method == "GET" :
        return redirect('board:article_detail', article_id)


def update_article(request, article_id) :
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'GET':
        return render(request, 'board/edit.html', {
            'article' : article
        })
    elif request.method == 'POST' :
        article.title = request.POST.get('title')
        article.content = request.POST.get('content')
        article.save()
        return redirect('board:article_detail', article_id)

def create_comment(request, article_id) :
    # 존재하지 않는 article number에 대한 제어
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST' :
        comment = Comment()
        comment.content = request.POST.get('content')
        comment.article_id = article.id
        comment.save()
    # 잘못된 (POST가 아닌)요청이 들어오더라도
    return redirect('board:article_detail', article_id)

def delete_comment(request, article_id, comment_id) :
    article = get_object_or_404(Article, id=article_id)
    comment = get_object_or_404(Comment,id=comment_id)
    if request.method == "POST" :
        comment.delete()
    return redirect('board:article_detail', article.id)

Django-Project/project_01/sns/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Posting, Comment

# Create your views here.
def posting_list(request) :
    postings = Posting.objects.order_by('-updated_at')
    return render(request, 'sns/list.html',{
        'postings':postings
    })

def posting_detail(request,posting_id):
    posting = get_object_or_404(Posting,id=posting_id)
    comments = posting.comment_set.order_by('-create_at') #TODO : Dock-typing
    return render(request,'sns/detail.html',{
        'posting':posting,
        'comments':comments
    })

def create_posting(request) :
    if request.method == 'POST' :
        """
        DB에 칼럼을 추가하는 방법
        [1]
        posting = Posting()
        posting.content = request.POST.get('content')
        ...
        posting.save()
        
        [2]
        posting = Posting(content=request.POST.get('content'),...)
        posting.save()

        [3]
        - 이건 save()를 할 필요가 없다.
        posting = Posting.objects.create(
            content=request.POST.get('content'),
            ...)
        """
        posting = Posting.objects.create(
            content=request.POST.get('content'),
            icon= request.POST.get('icon'),
            image=request.FILES.get('image'),
        )

        return redirect('sns:posting_detail', posting.id)
    else :
        return redirect('sns:posting_list')

def create_comment(request, posting_id) :
    posting = get_object_or_404(Posting, id =posting_id)
    if request.method == 'POST':
        comment = Comment()
        comment.posting_id = posting.id
        comment.content = request.POST.get('comment')
        comment.save()
    return redirect('sns:posting_detail',posting_id)

Django-Project/project_01/board/templates/board/_comment.html
<div id="comment">
    <div id="commentForm">
        <form action="{% url 'board:create_comment' article.id %}" method="POST">
            {% csrf_token %}
            <label for="content">content</label>
            <input type="text" name="content" id="content" placeholder="hit enter" autofocus>
        </form>
    </div>
    <div id="commentList">
        {% if comments %}
            {% for comment in comments %}
                <li>{{ comment.content }}</li>
                <form action="{% url 'board:delete_comment' article_id=article.id comment_id=comment.id %}" method="POST">
                    {%  csrf_token %}
                    <button type="submit">[ x ]</button>
                </form>
            {% endfor %}
        {% endif %}
    </div>
</div>

Django-Project/project_01/board/templates/board/base.html
<!doctype html>
<html lang='ko'>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Board-{% block title %}

    {% endblock %}</title>
</head>
<body>
{#<a href="{% url 'board:article_list' %}"><button>#}
{#    To Article list#}
{#</button></a>#}
{% block button %}
{% endblock %}

{% block body %}
{% endblock %}

</body>
</html>

Django-Project/project_01/board/templates/board/detail.html
{% extends 'board/base.html' %}
{% block title %}
    Detail Article
{% endblock %}
{% block button %}
    <button>
        <a href="{% url 'board:article_list' %}">Article List</a>
    </button>
{% endblock %}
{% block body %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.content }}</p>
    <div>
        <form action="{% url 'board:delete_article' article.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('삭제할래?')">삭제</button>
        </form>
    </div>
    <button><a href="{% url 'board:update_article' article.id %}">수정</a></button>
    <hr/>
    {% include 'board/_comment.html' %}
{% endblock %}

Django-Project/project_01/board/templates/board/edit.html
{% extends 'board/base.html' %}
{% block title %}
    Edit Article
{% endblock %}
{% block button %}
    <button>
        <a href="{% url 'board:article_list' %}">Article List</a>
    </button>
{% endblock %}
{% block body %}
    <form action="{% url 'board:update_article' article.id %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="title">title : </label>
            <input type="text" name="title" value="{{ article.title }}" id="title">
        </div>
        <div><label for="content">content</label>
            <textarea name="content" id="content" cols="30" rows="10">{{ article.content }}</textarea>
        </div>
        <div>
            <button type="submit">수정</button>
        </div>
    </form>
{% endblock %}

Django-Project/project_01/board/templates/board/list.html
{% extends 'board/base.html' %}
{% block title %}
    Article List
{% endblock %}
{% block button %}
    <button>
        <a href="{% url 'board:create_article' %}">New Article</a>
    </button>
{% endblock %}
{% block body %}
    <h1>Article List</h1>
    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                    <a href="{% url 'board:article_detail' article.id %}">
                        {{ article.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}

Django-Project/project_01/board/templates/board/new.html
{% extends 'board/base.html' %}
{% block title %}
    New Article
{% endblock %}
{% block button %}
    <a href="{% url 'board:article_list' %}">New Article</a>
{% endblock %}
{% block body %}
    <h1>New Article</h1>
    <form method="POST">
        {% csrf_token %}
        <div>
            <label for="title">title:</label>
            <input type="text" name="title" id="title">
        </div>
        <div>
            <label for="content">
                <textarea name="content" id="" cols="30" rows="10"></textarea>
            </label>
        </div>
        <div>
            <button type="submmit">제출</button>
        </div>
    </form>

{% endblock %}

Django-Project/project_01/sns/templates/sns/_comments.html
<!-- comment card-->
<div class="col-12 col-md-6">
            <div class="card mb-2">
                <div class="card-body">
                    <form action="{% url 'sns:create_comment' posting.id %}" method="post">
                        {% csrf_token %}
                        <label for="comment">comment</label>
                        <input type="text" name="comment" id="comment" class="form-control" autofocus>
                    </form>
                </div>
            </div>
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% if comments %}
                        {% for comment in comments %}
                            <li class="list-group-item mb-1">{{ comment.content }}</li>
                        {% endfor %}
                    {% else %}
                        <li class="list-group-item mb-1">No comments yet...</li>
                    {% endif %}
                </ul>
            </div>
        </div>

Django-Project/project_01/sns/templates/sns/_forms.html
<header class="mt-3">
    <form action="{% url 'sns:create_posting' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <!-- icon select tag -->
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    <option value="fas fa-question">?</option>
                    <option value="far fa-smile">:)</option>
                    <option value="far fa-angry">:(</option>
                    <option value="far fa-smile-wink">;)</option>
                    <option value="fab fa-angrycreative">angrycreative</option>
                </select>
            </div>
            <!-- content input tag -->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" placeholder="Feels like" class="form-control">
            </div>
            <!-- image file input tag -->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">upload</span>
                </div>
                <div class="custom-file">
                    <label for="image" class="custom-file-label">Select File</label>
                    <input type="file" id="image" name="image" class="custom-file-input" accept="image/*">
                </div>
            </div>
            <!-- submit button -->
            <div class="col-auto my-1">
                <button class="btn btn-primary" type="submit">submit</button>
            </div>

        </div>
    </form>

</header>

Django-Project/project_01/sns/templates/sns/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <!-- font-awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>SNS</title>
</head>
<body>
<!-- nav bar-->
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{% url 'sns:posting_list' %}" class="nav-link {% block list %}{% endblock %}">NewsFeed</a>
    </li>
    <li class="nav-item">
        <a href="" class="nav-link {% block detail %}{% endblock %}">Posting</a>
    </li>
</ul>
<div class="container">
    {% block body %}
    {% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

Django-Project/project_01/sns/templates/sns/detail.html
{% extends 'sns/base.html' %}
{% block detail %}
active
{% endblock %}
{% block body %}
<div class="row mt-3">
    <div class="col-12 col-md-6">
        <div class="card mb-1">
            {% if posting.image %}
                <img src="{{ posting.image.url }}"
                     alt="{{ posting.image }}"
                     class="card-img-top image-fulid">
            {% else %}
                <img src="https://picsum.photos/780/520?random">
            {% endif %}
            <div class="card-body">
                <i class="{{ posting.icon }} fa-2x"></i>
                <hr/>
                <p class="card-text">
                    {{ posting.content }}
                </p>
            </div>
        </div>
    </div>

{% include 'sns/_comments.html' %}
</div>
{% endblock %}

Django-Project/project_01/sns/templates/sns/list.html
{% extends 'sns/base.html' %}
{% block list %}
active
{% endblock %}
{% block body %}
{% include 'sns/_forms.html' %}

    {% if postings %}
        <section class="card-columns">
            {% for posting in postings %}
                <article class="card mb-2">
                    {% if posting.image %}
                        <a href="{% url 'sns:posting_detail' posting.id %}">
                            <img src="{{ posting.image_thumbnail.url }}"
                                 alt="{{ posting.image }}"
                                 class="card-img-top image-fluid">
                        </a>
                    {% else %}
                        <a href="{% url 'sns:posting_detail' posting.id %}">
                        <img src="https://picsum.photos/32{{ forloop.counter }}/580/?random"
                             alt="random-image-{{ forloop.counter }}"
                             class=" card-img-top image-fluid">
                        </a>
                    {% endif %}
                </article>

            {% endfor %}
        </section>
    {% endif %}
{% endblock %}